/* Generated by Yosys 0.66+115 (git sha1 5d7486115, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* top =  1  *)
(* src = "../src/top/riscv_cpu.v:3.1-420.10" *)
module riscv_cpu(clk, rst_n, debug_pc, debug_instruction, debug_writeback_data);
  (* src = "../src/top/riscv_cpu.v:4.16-4.19" *)
  input clk;
  wire clk;
  (* src = "../src/top/riscv_cpu.v:5.16-5.21" *)
  input rst_n;
  wire rst_n;
  (* src = "../src/top/riscv_cpu.v:6.24-6.32" *)
  output [31:0] debug_pc;
  wire [31:0] debug_pc;
  (* src = "../src/top/riscv_cpu.v:7.24-7.41" *)
  output [31:0] debug_instruction;
  wire [31:0] debug_instruction;
  (* src = "../src/top/riscv_cpu.v:8.24-8.44" *)
  output [31:0] debug_writeback_data;
  wire [31:0] debug_writeback_data;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  (* hdlname = "ALU_CTRL alu_control" *)
  (* src = "../src/control/alu_control.v:6.23-6.34" *)
  wire [3:0] \ALU_CTRL.alu_control ;
  (* hdlname = "ALU_CTRL alu_op" *)
  (* src = "../src/control/alu_control.v:3.23-3.29" *)
  wire [1:0] \ALU_CTRL.alu_op ;
  (* hdlname = "ALU_CTRL funct3" *)
  (* src = "../src/control/alu_control.v:4.23-4.29" *)
  wire [2:0] \ALU_CTRL.funct3 ;
  (* hdlname = "ALU_CTRL funct7" *)
  (* src = "../src/control/alu_control.v:5.23-5.29" *)
  wire [6:0] \ALU_CTRL.funct7 ;
  (* hdlname = "BRANCH branch" *)
  (* src = "../src/control/branch_unit.v:4.24-4.30" *)
  wire \BRANCH.branch ;
  (* hdlname = "BRANCH branch_taken" *)
  (* src = "../src/control/branch_unit.v:13.24-13.36" *)
  wire \BRANCH.branch_taken ;
  (* hdlname = "BRANCH equal" *)
  (* src = "../src/control/branch_unit.v:7.24-7.29" *)
  wire \BRANCH.equal ;
  (* hdlname = "BRANCH funct3" *)
  (* src = "../src/control/branch_unit.v:5.24-5.30" *)
  wire [2:0] \BRANCH.funct3 ;
  (* hdlname = "BRANCH not_equal" *)
  (* src = "../src/control/branch_unit.v:8.24-8.33" *)
  wire \BRANCH.not_equal ;
  (* hdlname = "BRANCH_ADDER a" *)
  (* src = "../src/common/adder.v:5.29-5.30" *)
  wire [31:0] \BRANCH_ADDER.a ;
  (* hdlname = "BRANCH_ADDER b" *)
  (* src = "../src/common/adder.v:6.29-6.30" *)
  wire [31:0] \BRANCH_ADDER.b ;
  (* hdlname = "BRANCH_ADDER sum" *)
  (* src = "../src/common/adder.v:7.29-7.32" *)
  wire [31:0] \BRANCH_ADDER.sum ;
  (* hdlname = "CMP a" *)
  (* src = "../src/datapath/comparator.v:6.34-6.35" *)
  wire [31:0] \CMP.a ;
  (* hdlname = "CMP b" *)
  (* src = "../src/datapath/comparator.v:7.34-7.35" *)
  wire [31:0] \CMP.b ;
  (* hdlname = "CMP equal" *)
  (* src = "../src/datapath/comparator.v:8.17-8.22" *)
  wire \CMP.equal ;
  (* hdlname = "CMP not_equal" *)
  (* src = "../src/datapath/comparator.v:9.17-9.26" *)
  wire \CMP.not_equal ;
  (* hdlname = "CONTROL alu_op" *)
  (* src = "../src/control/control_unit.v:12.23-12.29" *)
  wire [1:0] \CONTROL.alu_op ;
  (* hdlname = "CONTROL alu_src" *)
  (* src = "../src/control/control_unit.v:11.23-11.30" *)
  wire \CONTROL.alu_src ;
  (* hdlname = "CONTROL branch" *)
  (* src = "../src/control/control_unit.v:14.23-14.29" *)
  wire \CONTROL.branch ;
  (* hdlname = "CONTROL jump" *)
  (* src = "../src/control/control_unit.v:15.23-15.27" *)
  wire \CONTROL.jump ;
  (* hdlname = "CONTROL load_unsigned" *)
  (* src = "../src/control/control_unit.v:17.23-17.36" *)
  wire \CONTROL.load_unsigned ;
  (* hdlname = "CONTROL mem_read" *)
  (* src = "../src/control/control_unit.v:8.23-8.31" *)
  wire \CONTROL.mem_read ;
  (* hdlname = "CONTROL mem_write" *)
  (* src = "../src/control/control_unit.v:9.23-9.32" *)
  wire \CONTROL.mem_write ;
  (* hdlname = "CONTROL opcode" *)
  (* src = "../src/control/control_unit.v:4.23-4.29" *)
  wire [6:0] \CONTROL.opcode ;
  (* hdlname = "CONTROL reg_write" *)
  (* src = "../src/control/control_unit.v:6.23-6.32" *)
  wire \CONTROL.reg_write ;
  (* hdlname = "CONTROL use_pc_as_operand_a" *)
  (* src = "../src/control/control_unit.v:27.23-27.42" *)
  wire \CONTROL.use_pc_as_operand_a ;
  (* hdlname = "CONTROL wb_sel" *)
  (* src = "../src/control/control_unit.v:23.23-23.29" *)
  wire [1:0] \CONTROL.wb_sel ;
  (* hdlname = "DECODER funct3" *)
  (* src = "../src/control/decoder.v:6.24-6.30" *)
  wire [2:0] \DECODER.funct3 ;
  (* hdlname = "DECODER funct7" *)
  (* src = "../src/control/decoder.v:9.24-9.30" *)
  wire [6:0] \DECODER.funct7 ;
  (* hdlname = "DECODER instruction" *)
  (* src = "../src/control/decoder.v:3.24-3.35" *)
  wire [31:0] \DECODER.instruction ;
  (* hdlname = "DECODER opcode" *)
  (* src = "../src/control/decoder.v:4.24-4.30" *)
  wire [6:0] \DECODER.opcode ;
  (* hdlname = "DECODER rd" *)
  (* src = "../src/control/decoder.v:5.24-5.26" *)
  wire [4:0] \DECODER.rd ;
  (* hdlname = "DECODER rs1" *)
  (* src = "../src/control/decoder.v:7.24-7.27" *)
  wire [4:0] \DECODER.rs1 ;
  (* hdlname = "DECODER rs2" *)
  (* src = "../src/control/decoder.v:8.24-8.27" *)
  wire [4:0] \DECODER.rs2 ;
  (* hdlname = "EX_MEM alu_result" *)
  (* src = "../src/pipeline/ex_mem_reg.v:15.34-15.44" *)
  wire [31:0] \EX_MEM.alu_result ;
  (* hdlname = "EX_MEM alu_result_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:25.34-25.48" *)
  wire [31:0] \EX_MEM.alu_result_out ;
  (* hdlname = "EX_MEM clk" *)
  (* src = "../src/pipeline/ex_mem_reg.v:6.34-6.37" *)
  wire \EX_MEM.clk ;
  (* hdlname = "EX_MEM flush" *)
  (* src = "../src/pipeline/ex_mem_reg.v:8.34-8.39" *)
  wire \EX_MEM.flush ;
  (* hdlname = "EX_MEM immediate" *)
  (* src = "../src/pipeline/ex_mem_reg.v:18.34-18.43" *)
  wire [31:0] \EX_MEM.immediate ;
  (* hdlname = "EX_MEM immediate_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:28.34-28.47" *)
  wire [31:0] \EX_MEM.immediate_out ;
  (* hdlname = "EX_MEM mem_read" *)
  (* src = "../src/pipeline/ex_mem_reg.v:11.34-11.42" *)
  wire \EX_MEM.mem_read ;
  (* hdlname = "EX_MEM mem_read_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:22.34-22.46" *)
  wire \EX_MEM.mem_read_out ;
  (* hdlname = "EX_MEM mem_write" *)
  (* src = "../src/pipeline/ex_mem_reg.v:12.34-12.43" *)
  wire \EX_MEM.mem_write ;
  (* hdlname = "EX_MEM mem_write_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:23.34-23.47" *)
  wire \EX_MEM.mem_write_out ;
  (* hdlname = "EX_MEM pc_plus4" *)
  (* src = "../src/pipeline/ex_mem_reg.v:17.34-17.42" *)
  wire [31:0] \EX_MEM.pc_plus4 ;
  (* hdlname = "EX_MEM pc_plus4_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:27.34-27.46" *)
  wire [31:0] \EX_MEM.pc_plus4_out ;
  (* hdlname = "EX_MEM rd" *)
  (* src = "../src/pipeline/ex_mem_reg.v:19.34-19.36" *)
  wire [4:0] \EX_MEM.rd ;
  (* hdlname = "EX_MEM rd_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:29.34-29.40" *)
  wire [4:0] \EX_MEM.rd_out ;
  (* hdlname = "EX_MEM rs2_data" *)
  (* src = "../src/pipeline/ex_mem_reg.v:16.34-16.42" *)
  wire [31:0] \EX_MEM.rs2_data ;
  (* hdlname = "EX_MEM rst_n" *)
  (* src = "../src/pipeline/ex_mem_reg.v:7.34-7.39" *)
  wire \EX_MEM.rst_n ;
  (* hdlname = "EX_MEM wb_sel" *)
  (* src = "../src/pipeline/ex_mem_reg.v:13.34-13.40" *)
  wire [1:0] \EX_MEM.wb_sel ;
  (* hdlname = "EX_MEM wb_sel_out" *)
  (* src = "../src/pipeline/ex_mem_reg.v:24.34-24.44" *)
  wire [1:0] \EX_MEM.wb_sel_out ;
  (* hdlname = "EX_STAGE ALU alu_control" *)
  (* src = "../src/datapath/alu.v:7.34-7.45" *)
  wire [3:0] \EX_STAGE.ALU.alu_control ;
  (* hdlname = "EX_STAGE ALU operand_a" *)
  (* src = "../src/datapath/alu.v:5.34-5.43" *)
  wire [31:0] \EX_STAGE.ALU.operand_a ;
  (* hdlname = "EX_STAGE ALU operand_b" *)
  (* src = "../src/datapath/alu.v:6.34-6.43" *)
  wire [31:0] \EX_STAGE.ALU.operand_b ;
  (* hdlname = "EX_STAGE ALU result" *)
  (* src = "../src/datapath/alu.v:8.34-8.40" *)
  wire [31:0] \EX_STAGE.ALU.result ;
  (* hdlname = "EX_STAGE alu_control" *)
  (* src = "../src/datapath/execute_stage.v:12.34-12.45" *)
  wire [3:0] \EX_STAGE.alu_control ;
  (* hdlname = "EX_STAGE alu_result" *)
  (* src = "../src/datapath/execute_stage.v:14.34-14.44" *)
  wire [31:0] \EX_STAGE.alu_result ;
  (* hdlname = "EX_STAGE immediate" *)
  (* src = "../src/datapath/execute_stage.v:9.34-9.43" *)
  wire [31:0] \EX_STAGE.immediate ;
  (* hdlname = "EX_STAGE operand_a" *)
  (* src = "../src/datapath/execute_stage.v:22.23-22.32" *)
  wire [31:0] \EX_STAGE.operand_a ;
  (* hdlname = "EX_STAGE operand_b" *)
  (* src = "../src/datapath/execute_stage.v:24.23-24.32" *)
  wire [31:0] \EX_STAGE.operand_b ;
  (* hdlname = "EX_STAGE pc" *)
  (* src = "../src/datapath/execute_stage.v:6.34-6.36" *)
  wire [31:0] \EX_STAGE.pc ;
  (* hdlname = "EX_STAGE rs1_data" *)
  (* src = "../src/datapath/execute_stage.v:7.34-7.42" *)
  wire [31:0] \EX_STAGE.rs1_data ;
  (* hdlname = "EX_STAGE rs2_data" *)
  (* src = "../src/datapath/execute_stage.v:8.34-8.42" *)
  wire [31:0] \EX_STAGE.rs2_data ;
  (* hdlname = "EX_STAGE use_pc_as_operand_a" *)
  (* src = "../src/datapath/execute_stage.v:11.34-11.53" *)
  wire \EX_STAGE.use_pc_as_operand_a ;
  (* hdlname = "FLUSH branch_taken" *)
  (* src = "../src/control/flush_unit.v:7.17-7.29" *)
  wire \FLUSH.branch_taken ;
  (* hdlname = "FLUSH id_ex_flush" *)
  (* src = "../src/control/flush_unit.v:11.17-11.28" *)
  wire \FLUSH.id_ex_flush ;
  (* hdlname = "FLUSH if_id_flush" *)
  (* src = "../src/control/flush_unit.v:10.17-10.28" *)
  wire \FLUSH.if_id_flush ;
  (* hdlname = "FLUSH jump" *)
  (* src = "../src/control/flush_unit.v:8.17-8.21" *)
  wire \FLUSH.jump ;
  (* hdlname = "FORWARD ex_mem_rd" *)
  (* src = "../src/control/forwarding_unit.v:4.23-4.32" *)
  wire [4:0] \FORWARD.ex_mem_rd ;
  (* hdlname = "FORWARD forward_a" *)
  (* src = "../src/control/forwarding_unit.v:9.23-9.32" *)
  wire [1:0] \FORWARD.forward_a ;
  (* hdlname = "FORWARD forward_b" *)
  (* src = "../src/control/forwarding_unit.v:10.23-10.32" *)
  wire [1:0] \FORWARD.forward_b ;
  (* hdlname = "FORWARD id_ex_rs1" *)
  (* src = "../src/control/forwarding_unit.v:7.23-7.32" *)
  wire [4:0] \FORWARD.id_ex_rs1 ;
  (* hdlname = "FORWARD id_ex_rs2" *)
  (* src = "../src/control/forwarding_unit.v:8.23-8.32" *)
  wire [4:0] \FORWARD.id_ex_rs2 ;
  (* hdlname = "FORWARD mem_wb_rd" *)
  (* src = "../src/control/forwarding_unit.v:6.23-6.32" *)
  wire [4:0] \FORWARD.mem_wb_rd ;
  (* hdlname = "FORWARD_A in0" *)
  (* src = "../src/common/mux4.v:6.34-6.37" *)
  wire [31:0] \FORWARD_A.in0 ;
  (* hdlname = "FORWARD_A in1" *)
  (* src = "../src/common/mux4.v:7.34-7.37" *)
  wire [31:0] \FORWARD_A.in1 ;
  (* hdlname = "FORWARD_A in2" *)
  (* src = "../src/common/mux4.v:8.34-8.37" *)
  wire [31:0] \FORWARD_A.in2 ;
  (* hdlname = "FORWARD_A in3" *)
  (* src = "../src/common/mux4.v:9.34-9.37" *)
  wire [31:0] \FORWARD_A.in3 ;
  (* hdlname = "FORWARD_A out" *)
  (* src = "../src/common/mux4.v:11.34-11.37" *)
  wire [31:0] \FORWARD_A.out ;
  (* hdlname = "FORWARD_A sel" *)
  (* src = "../src/common/mux4.v:10.23-10.26" *)
  wire [1:0] \FORWARD_A.sel ;
  (* hdlname = "FORWARD_B in0" *)
  (* src = "../src/common/mux4.v:6.34-6.37" *)
  wire [31:0] \FORWARD_B.in0 ;
  (* hdlname = "FORWARD_B in1" *)
  (* src = "../src/common/mux4.v:7.34-7.37" *)
  wire [31:0] \FORWARD_B.in1 ;
  (* hdlname = "FORWARD_B in2" *)
  (* src = "../src/common/mux4.v:8.34-8.37" *)
  wire [31:0] \FORWARD_B.in2 ;
  (* hdlname = "FORWARD_B in3" *)
  (* src = "../src/common/mux4.v:9.34-9.37" *)
  wire [31:0] \FORWARD_B.in3 ;
  (* hdlname = "FORWARD_B out" *)
  (* src = "../src/common/mux4.v:11.34-11.37" *)
  wire [31:0] \FORWARD_B.out ;
  (* hdlname = "FORWARD_B sel" *)
  (* src = "../src/common/mux4.v:10.23-10.26" *)
  wire [1:0] \FORWARD_B.sel ;
  (* hdlname = "HAZARD id_ex_flush" *)
  (* src = "../src/control/hazard_detection_unit.v:9.23-9.34" *)
  wire \HAZARD.id_ex_flush ;
  (* hdlname = "HAZARD id_ex_mem_read" *)
  (* src = "../src/control/hazard_detection_unit.v:3.23-3.37" *)
  wire \HAZARD.id_ex_mem_read ;
  (* hdlname = "HAZARD id_ex_rd" *)
  (* src = "../src/control/hazard_detection_unit.v:4.23-4.31" *)
  wire [4:0] \HAZARD.id_ex_rd ;
  (* hdlname = "HAZARD if_id_rs1" *)
  (* src = "../src/control/hazard_detection_unit.v:5.23-5.32" *)
  wire [4:0] \HAZARD.if_id_rs1 ;
  (* hdlname = "HAZARD if_id_rs2" *)
  (* src = "../src/control/hazard_detection_unit.v:6.23-6.32" *)
  wire [4:0] \HAZARD.if_id_rs2 ;
  (* hdlname = "HAZARD if_id_write" *)
  (* src = "../src/control/hazard_detection_unit.v:8.23-8.34" *)
  wire \HAZARD.if_id_write ;
  (* hdlname = "HAZARD pc_write" *)
  (* src = "../src/control/hazard_detection_unit.v:7.23-7.31" *)
  wire \HAZARD.pc_write ;
  (* hdlname = "ID_EX alu_op" *)
  (* src = "../src/pipeline/id_ex_reg.v:14.37-14.43" *)
  wire [1:0] \ID_EX.alu_op ;
  (* hdlname = "ID_EX alu_src" *)
  (* src = "../src/pipeline/id_ex_reg.v:13.37-13.44" *)
  wire \ID_EX.alu_src ;
  (* hdlname = "ID_EX branch" *)
  (* src = "../src/pipeline/id_ex_reg.v:16.37-16.43" *)
  wire \ID_EX.branch ;
  (* hdlname = "ID_EX branch_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:40.37-40.47" *)
  wire \ID_EX.branch_out ;
  (* hdlname = "ID_EX clk" *)
  (* src = "../src/pipeline/id_ex_reg.v:6.37-6.40" *)
  wire \ID_EX.clk ;
  (* hdlname = "ID_EX flush" *)
  (* src = "../src/pipeline/id_ex_reg.v:8.37-8.42" *)
  wire \ID_EX.flush ;
  (* hdlname = "ID_EX funct3" *)
  (* src = "../src/pipeline/id_ex_reg.v:21.37-21.43" *)
  wire [2:0] \ID_EX.funct3 ;
  (* hdlname = "ID_EX funct3_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:45.37-45.47" *)
  wire [2:0] \ID_EX.funct3_out ;
  (* hdlname = "ID_EX funct7" *)
  (* src = "../src/pipeline/id_ex_reg.v:22.37-22.43" *)
  wire [6:0] \ID_EX.funct7 ;
  (* hdlname = "ID_EX funct7_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:46.37-46.47" *)
  wire [6:0] \ID_EX.funct7_out ;
  (* hdlname = "ID_EX immediate" *)
  (* src = "../src/pipeline/id_ex_reg.v:27.37-27.46" *)
  wire [31:0] \ID_EX.immediate ;
  (* hdlname = "ID_EX immediate_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:51.37-51.50" *)
  wire [31:0] \ID_EX.immediate_out ;
  (* hdlname = "ID_EX jump" *)
  (* src = "../src/pipeline/id_ex_reg.v:17.37-17.41" *)
  wire \ID_EX.jump ;
  (* hdlname = "ID_EX jump_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:41.37-41.45" *)
  wire \ID_EX.jump_out ;
  (* hdlname = "ID_EX load_unsigned" *)
  (* src = "../src/pipeline/id_ex_reg.v:18.37-18.50" *)
  wire \ID_EX.load_unsigned ;
  (* hdlname = "ID_EX load_unsigned_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:42.37-42.54" *)
  wire \ID_EX.load_unsigned_out ;
  (* hdlname = "ID_EX mem_read" *)
  (* src = "../src/pipeline/id_ex_reg.v:11.37-11.45" *)
  wire \ID_EX.mem_read ;
  (* hdlname = "ID_EX mem_read_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:33.37-33.49" *)
  wire \ID_EX.mem_read_out ;
  (* hdlname = "ID_EX mem_write" *)
  (* src = "../src/pipeline/id_ex_reg.v:12.37-12.46" *)
  wire \ID_EX.mem_write ;
  (* hdlname = "ID_EX mem_write_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:34.37-34.50" *)
  wire \ID_EX.mem_write_out ;
  (* hdlname = "ID_EX pc" *)
  (* src = "../src/pipeline/id_ex_reg.v:24.37-24.39" *)
  wire [31:0] \ID_EX.pc ;
  (* hdlname = "ID_EX pc_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:48.37-48.43" *)
  wire [31:0] \ID_EX.pc_out ;
  (* hdlname = "ID_EX rd" *)
  (* src = "../src/pipeline/id_ex_reg.v:30.37-30.39" *)
  wire [4:0] \ID_EX.rd ;
  (* hdlname = "ID_EX rd_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:54.37-54.43" *)
  wire [4:0] \ID_EX.rd_out ;
  (* hdlname = "ID_EX reg_write" *)
  (* src = "../src/pipeline/id_ex_reg.v:10.37-10.46" *)
  wire \ID_EX.reg_write ;
  (* hdlname = "ID_EX rs1" *)
  (* src = "../src/pipeline/id_ex_reg.v:28.37-28.40" *)
  wire [4:0] \ID_EX.rs1 ;
  (* hdlname = "ID_EX rs1_data" *)
  (* src = "../src/pipeline/id_ex_reg.v:25.37-25.45" *)
  wire [31:0] \ID_EX.rs1_data ;
  (* hdlname = "ID_EX rs1_data_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:49.37-49.49" *)
  wire [31:0] \ID_EX.rs1_data_out ;
  (* hdlname = "ID_EX rs1_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:52.37-52.44" *)
  wire [4:0] \ID_EX.rs1_out ;
  (* hdlname = "ID_EX rs2" *)
  (* src = "../src/pipeline/id_ex_reg.v:29.37-29.40" *)
  wire [4:0] \ID_EX.rs2 ;
  (* hdlname = "ID_EX rs2_data" *)
  (* src = "../src/pipeline/id_ex_reg.v:26.37-26.45" *)
  wire [31:0] \ID_EX.rs2_data ;
  (* hdlname = "ID_EX rs2_data_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:50.37-50.49" *)
  wire [31:0] \ID_EX.rs2_data_out ;
  (* hdlname = "ID_EX rs2_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:53.37-53.44" *)
  wire [4:0] \ID_EX.rs2_out ;
  (* hdlname = "ID_EX rst_n" *)
  (* src = "../src/pipeline/id_ex_reg.v:7.37-7.42" *)
  wire \ID_EX.rst_n ;
  (* hdlname = "ID_EX use_pc_as_operand_a" *)
  (* src = "../src/pipeline/id_ex_reg.v:19.37-19.56" *)
  wire \ID_EX.use_pc_as_operand_a ;
  (* hdlname = "ID_EX use_pc_as_operand_a_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:43.37-43.60" *)
  wire \ID_EX.use_pc_as_operand_a_out ;
  (* hdlname = "ID_EX wb_sel" *)
  (* src = "../src/pipeline/id_ex_reg.v:15.37-15.43" *)
  wire [1:0] \ID_EX.wb_sel ;
  (* hdlname = "ID_EX wb_sel_out" *)
  (* src = "../src/pipeline/id_ex_reg.v:38.37-38.47" *)
  wire [1:0] \ID_EX.wb_sel_out ;
  (* hdlname = "ID_EX_PC4 a" *)
  (* src = "../src/common/adder.v:5.29-5.30" *)
  wire [31:0] \ID_EX_PC4.a ;
  (* hdlname = "ID_EX_PC4 b" *)
  (* src = "../src/common/adder.v:6.29-6.30" *)
  wire [31:0] \ID_EX_PC4.b ;
  (* hdlname = "ID_EX_PC4 sum" *)
  (* src = "../src/common/adder.v:7.29-7.32" *)
  wire [31:0] \ID_EX_PC4.sum ;
  (* hdlname = "IF_ID clk" *)
  (* src = "../src/pipeline/if_id_reg.v:5.34-5.37" *)
  wire \IF_ID.clk ;
  (* hdlname = "IF_ID flush" *)
  (* src = "../src/pipeline/if_id_reg.v:8.34-8.39" *)
  wire \IF_ID.flush ;
  (* hdlname = "IF_ID instruction" *)
  (* src = "../src/pipeline/if_id_reg.v:10.34-10.45" *)
  wire [31:0] \IF_ID.instruction ;
  (* hdlname = "IF_ID instruction_out" *)
  (* src = "../src/pipeline/if_id_reg.v:12.34-12.49" *)
  wire [31:0] \IF_ID.instruction_out ;
  (* hdlname = "IF_ID pc" *)
  (* src = "../src/pipeline/if_id_reg.v:9.34-9.36" *)
  wire [31:0] \IF_ID.pc ;
  (* hdlname = "IF_ID pc_out" *)
  (* src = "../src/pipeline/if_id_reg.v:11.34-11.40" *)
  wire [31:0] \IF_ID.pc_out ;
  (* hdlname = "IF_ID rst_n" *)
  (* src = "../src/pipeline/if_id_reg.v:6.34-6.39" *)
  wire \IF_ID.rst_n ;
  (* hdlname = "IF_ID stall" *)
  (* src = "../src/pipeline/if_id_reg.v:7.34-7.39" *)
  wire \IF_ID.stall ;
  (* hdlname = "IMEM i" *)
  (* src = "../src/memory/instruction_memory.v:13.9-13.10" *)
  wire signed [31:0] \IMEM.i ;
  (* hdlname = "IMEM instruction" *)
  (* src = "../src/memory/instruction_memory.v:8.37-8.48" *)
  wire [31:0] \IMEM.instruction ;
  (* hdlname = "IMEM pc" *)
  (* src = "../src/memory/instruction_memory.v:7.37-7.39" *)
  wire [31:0] \IMEM.pc ;
  (* hdlname = "IMEM word_addr" *)
  (* src = "../src/memory/instruction_memory.v:23.23-23.32" *)
  wire [9:0] \IMEM.word_addr ;
  (* hdlname = "IMM_GEN immediate" *)
  (* src = "../src/datapath/immediate_generator.v:4.24-4.33" *)
  wire [31:0] \IMM_GEN.immediate ;
  (* hdlname = "IMM_GEN instruction" *)
  (* src = "../src/datapath/immediate_generator.v:3.24-3.35" *)
  wire [31:0] \IMM_GEN.instruction ;
  (* hdlname = "IMM_GEN opcode" *)
  (* src = "../src/datapath/immediate_generator.v:7.16-7.22" *)
  wire [6:0] \IMM_GEN.opcode ;
  (* hdlname = "MEM_STAGE DMEM address" *)
  (* src = "../src/memory/data_memory.v:17.37-17.44" *)
  wire [31:0] \MEM_STAGE.DMEM.address ;
  (* hdlname = "MEM_STAGE DMEM clk" *)
  (* src = "../src/memory/data_memory.v:11.37-11.40" *)
  wire \MEM_STAGE.DMEM.clk ;
  (* hdlname = "MEM_STAGE DMEM i" *)
  (* src = "../src/memory/data_memory.v:25.9-25.10" *)
  wire signed [31:0] \MEM_STAGE.DMEM.i ;
  (* hdlname = "MEM_STAGE DMEM mem_read" *)
  (* src = "../src/memory/data_memory.v:14.37-14.45" *)
  wire \MEM_STAGE.DMEM.mem_read ;
  (* hdlname = "MEM_STAGE DMEM mem_write" *)
  (* src = "../src/memory/data_memory.v:15.37-15.46" *)
  wire \MEM_STAGE.DMEM.mem_write ;
  (* hdlname = "MEM_STAGE DMEM word_addr" *)
  (* src = "../src/memory/data_memory.v:37.23-37.32" *)
  wire [9:0] \MEM_STAGE.DMEM.word_addr ;
  (* hdlname = "MEM_STAGE address" *)
  (* src = "../src/memory/memory_stage.v:11.37-11.44" *)
  wire [31:0] \MEM_STAGE.address ;
  (* hdlname = "MEM_STAGE clk" *)
  (* src = "../src/memory/memory_stage.v:6.37-6.40" *)
  wire \MEM_STAGE.clk ;
  (* hdlname = "MEM_STAGE mem_read" *)
  (* src = "../src/memory/memory_stage.v:8.37-8.45" *)
  wire \MEM_STAGE.mem_read ;
  (* hdlname = "MEM_STAGE mem_write" *)
  (* src = "../src/memory/memory_stage.v:9.37-9.46" *)
  wire \MEM_STAGE.mem_write ;
  (* hdlname = "MEM_WB alu_result" *)
  (* src = "../src/pipeline/mem_wb_reg.v:14.34-14.44" *)
  wire [31:0] \MEM_WB.alu_result ;
  (* hdlname = "MEM_WB alu_result_out" *)
  (* src = "../src/pipeline/mem_wb_reg.v:22.34-22.48" *)
  wire [31:0] \MEM_WB.alu_result_out ;
  (* hdlname = "MEM_WB clk" *)
  (* src = "../src/pipeline/mem_wb_reg.v:6.34-6.37" *)
  wire \MEM_WB.clk ;
  (* hdlname = "MEM_WB flush" *)
  (* src = "../src/pipeline/mem_wb_reg.v:8.34-8.39" *)
  wire \MEM_WB.flush ;
  (* hdlname = "MEM_WB immediate" *)
  (* src = "../src/pipeline/mem_wb_reg.v:16.34-16.43" *)
  wire [31:0] \MEM_WB.immediate ;
  (* hdlname = "MEM_WB immediate_out" *)
  (* src = "../src/pipeline/mem_wb_reg.v:24.34-24.47" *)
  wire [31:0] \MEM_WB.immediate_out ;
  (* hdlname = "MEM_WB pc_plus4" *)
  (* src = "../src/pipeline/mem_wb_reg.v:15.34-15.42" *)
  wire [31:0] \MEM_WB.pc_plus4 ;
  (* hdlname = "MEM_WB pc_plus4_out" *)
  (* src = "../src/pipeline/mem_wb_reg.v:23.34-23.46" *)
  wire [31:0] \MEM_WB.pc_plus4_out ;
  (* hdlname = "MEM_WB rd" *)
  (* src = "../src/pipeline/mem_wb_reg.v:17.34-17.36" *)
  wire [4:0] \MEM_WB.rd ;
  (* hdlname = "MEM_WB rd_out" *)
  (* src = "../src/pipeline/mem_wb_reg.v:25.34-25.40" *)
  wire [4:0] \MEM_WB.rd_out ;
  (* hdlname = "MEM_WB rst_n" *)
  (* src = "../src/pipeline/mem_wb_reg.v:7.34-7.39" *)
  wire \MEM_WB.rst_n ;
  (* hdlname = "MEM_WB wb_sel" *)
  (* src = "../src/pipeline/mem_wb_reg.v:11.34-11.40" *)
  wire [1:0] \MEM_WB.wb_sel ;
  (* hdlname = "MEM_WB wb_sel_out" *)
  (* src = "../src/pipeline/mem_wb_reg.v:20.34-20.44" *)
  wire [1:0] \MEM_WB.wb_sel_out ;
  (* hdlname = "PC clk" *)
  (* src = "../src/common/program_counter.v:6.37-6.40" *)
  wire \PC.clk ;
  (* hdlname = "PC next_pc" *)
  (* src = "../src/common/program_counter.v:11.37-11.44" *)
  wire [31:0] \PC.next_pc ;
  (* hdlname = "PC pc" *)
  (* src = "../src/common/program_counter.v:13.37-13.39" *)
  wire [31:0] \PC.pc ;
  (* hdlname = "PC pc_en" *)
  (* src = "../src/common/program_counter.v:9.37-9.42" *)
  wire \PC.pc_en ;
  (* hdlname = "PC rst_n" *)
  (* src = "../src/common/program_counter.v:7.37-7.42" *)
  wire \PC.rst_n ;
  (* hdlname = "PC_ADDER a" *)
  (* src = "../src/common/adder.v:5.29-5.30" *)
  wire [31:0] \PC_ADDER.a ;
  (* hdlname = "PC_ADDER b" *)
  (* src = "../src/common/adder.v:6.29-6.30" *)
  wire [31:0] \PC_ADDER.b ;
  (* hdlname = "PC_ADDER sum" *)
  (* src = "../src/common/adder.v:7.29-7.32" *)
  wire [31:0] \PC_ADDER.sum ;
  (* hdlname = "RF clk" *)
  (* src = "../src/datapath/register_file.v:10.37-10.40" *)
  wire \RF.clk ;
  (* hdlname = "RF i" *)
  (* src = "../src/datapath/register_file.v:26.9-26.10" *)
  wire signed [31:0] \RF.i ;
  (* hdlname = "RF rd_addr" *)
  (* src = "../src/datapath/register_file.v:14.37-14.44" *)
  wire [4:0] \RF.rd_addr ;
  (* hdlname = "RF rd_data" *)
  (* src = "../src/datapath/register_file.v:15.37-15.44" *)
  wire [31:0] \RF.rd_data ;
  (* hdlname = "RF registers[10]" *)
  wire [31:0] \RF.registers[10] ;
  (* hdlname = "RF registers[11]" *)
  wire [31:0] \RF.registers[11] ;
  (* hdlname = "RF registers[12]" *)
  wire [31:0] \RF.registers[12] ;
  (* hdlname = "RF registers[13]" *)
  wire [31:0] \RF.registers[13] ;
  (* hdlname = "RF registers[14]" *)
  wire [31:0] \RF.registers[14] ;
  (* hdlname = "RF registers[15]" *)
  wire [31:0] \RF.registers[15] ;
  (* hdlname = "RF registers[16]" *)
  wire [31:0] \RF.registers[16] ;
  (* hdlname = "RF registers[17]" *)
  wire [31:0] \RF.registers[17] ;
  (* hdlname = "RF registers[18]" *)
  wire [31:0] \RF.registers[18] ;
  (* hdlname = "RF registers[19]" *)
  wire [31:0] \RF.registers[19] ;
  (* hdlname = "RF registers[1]" *)
  wire [31:0] \RF.registers[1] ;
  (* hdlname = "RF registers[20]" *)
  wire [31:0] \RF.registers[20] ;
  (* hdlname = "RF registers[21]" *)
  wire [31:0] \RF.registers[21] ;
  (* hdlname = "RF registers[22]" *)
  wire [31:0] \RF.registers[22] ;
  (* hdlname = "RF registers[23]" *)
  wire [31:0] \RF.registers[23] ;
  (* hdlname = "RF registers[24]" *)
  wire [31:0] \RF.registers[24] ;
  (* hdlname = "RF registers[25]" *)
  wire [31:0] \RF.registers[25] ;
  (* hdlname = "RF registers[26]" *)
  wire [31:0] \RF.registers[26] ;
  (* hdlname = "RF registers[27]" *)
  wire [31:0] \RF.registers[27] ;
  (* hdlname = "RF registers[28]" *)
  wire [31:0] \RF.registers[28] ;
  (* hdlname = "RF registers[29]" *)
  wire [31:0] \RF.registers[29] ;
  (* hdlname = "RF registers[2]" *)
  wire [31:0] \RF.registers[2] ;
  (* hdlname = "RF registers[30]" *)
  wire [31:0] \RF.registers[30] ;
  (* hdlname = "RF registers[3]" *)
  wire [31:0] \RF.registers[3] ;
  (* hdlname = "RF registers[4]" *)
  wire [31:0] \RF.registers[4] ;
  (* hdlname = "RF registers[5]" *)
  wire [31:0] \RF.registers[5] ;
  (* hdlname = "RF registers[6]" *)
  wire [31:0] \RF.registers[6] ;
  (* hdlname = "RF registers[7]" *)
  wire [31:0] \RF.registers[7] ;
  (* hdlname = "RF registers[8]" *)
  wire [31:0] \RF.registers[8] ;
  (* hdlname = "RF registers[9]" *)
  wire [31:0] \RF.registers[9] ;
  (* hdlname = "RF rs1_addr" *)
  (* src = "../src/datapath/register_file.v:17.37-17.45" *)
  wire [4:0] \RF.rs1_addr ;
  (* hdlname = "RF rs1_data" *)
  (* src = "../src/datapath/register_file.v:18.37-18.45" *)
  wire [31:0] \RF.rs1_data ;
  (* hdlname = "RF rs2_addr" *)
  (* src = "../src/datapath/register_file.v:20.37-20.45" *)
  wire [4:0] \RF.rs2_addr ;
  (* hdlname = "RF rs2_data" *)
  (* src = "../src/datapath/register_file.v:21.37-21.45" *)
  wire [31:0] \RF.rs2_data ;
  (* hdlname = "RF rst_n" *)
  (* src = "../src/datapath/register_file.v:11.37-11.42" *)
  wire \RF.rst_n ;
  (* hdlname = "WB_STAGE alu_result" *)
  (* src = "../src/writeback/writeback_stage.v:6.33-6.43" *)
  wire [31:0] \WB_STAGE.alu_result ;
  (* hdlname = "WB_STAGE immediate" *)
  (* src = "../src/writeback/writeback_stage.v:9.33-9.42" *)
  wire [31:0] \WB_STAGE.immediate ;
  (* hdlname = "WB_STAGE pc_plus4" *)
  (* src = "../src/writeback/writeback_stage.v:8.33-8.41" *)
  wire [31:0] \WB_STAGE.pc_plus4 ;
  (* hdlname = "WB_STAGE wb_sel" *)
  (* src = "../src/writeback/writeback_stage.v:15.22-15.28" *)
  wire [1:0] \WB_STAGE.wb_sel ;
  (* hdlname = "WB_STAGE writeback_data" *)
  (* src = "../src/writeback/writeback_stage.v:17.33-17.47" *)
  wire [31:0] \WB_STAGE.writeback_data ;
  (* src = "../src/top/riscv_cpu.v:42.12-42.30" *)
  wire [3:0] alu_control_signal;
  (* src = "../src/top/riscv_cpu.v:31.12-31.18" *)
  wire [1:0] alu_op;
  (* src = "../src/top/riscv_cpu.v:38.13-38.23" *)
  wire [31:0] alu_result;
  (* src = "../src/top/riscv_cpu.v:27.6-27.13" *)
  wire alu_src;
  (* src = "../src/top/riscv_cpu.v:28.6-28.12" *)
  wire branch;
  (* src = "../src/top/riscv_cpu.v:47.6-47.18" *)
  wire branch_taken;
  (* src = "../src/top/riscv_cpu.v:46.13-46.26" *)
  wire [31:0] branch_target;
  (* src = "../src/top/riscv_cpu.v:51.6-51.8" *)
  wire eq;
  (* src = "../src/top/riscv_cpu.v:96.13-96.30" *)
  wire [31:0] ex_mem_alu_result;
  (* src = "../src/top/riscv_cpu.v:207.6-207.18" *)
  wire ex_mem_flush;
  (* src = "../src/top/riscv_cpu.v:99.13-99.29" *)
  wire [31:0] ex_mem_immediate;
  (* src = "../src/top/riscv_cpu.v:93.13-93.28" *)
  wire ex_mem_mem_read;
  (* src = "../src/top/riscv_cpu.v:94.13-94.29" *)
  wire ex_mem_mem_write;
  (* src = "../src/top/riscv_cpu.v:98.13-98.28" *)
  wire [31:0] ex_mem_pc_plus4;
  (* src = "../src/top/riscv_cpu.v:100.13-100.22" *)
  wire [4:0] ex_mem_rd;
  (* src = "../src/top/riscv_cpu.v:95.13-95.26" *)
  wire [1:0] ex_mem_wb_sel;
  (* src = "../src/top/riscv_cpu.v:110.12-110.21" *)
  wire [1:0] forward_a;
  (* src = "../src/top/riscv_cpu.v:111.12-111.21" *)
  wire [1:0] forward_b;
  (* src = "../src/top/riscv_cpu.v:112.13-112.24" *)
  wire [31:0] forward_rs1;
  (* src = "../src/top/riscv_cpu.v:113.13-113.24" *)
  wire [31:0] forward_rs2;
  (* src = "../src/top/riscv_cpu.v:19.12-19.18" *)
  wire [2:0] funct3;
  (* src = "../src/top/riscv_cpu.v:22.12-22.18" *)
  wire [6:0] funct7;
  (* src = "../src/top/riscv_cpu.v:85.13-85.25" *)
  wire id_ex_branch;
  (* src = "../src/top/riscv_cpu.v:90.13-90.24" *)
  wire id_ex_flush;
  (* src = "../src/top/riscv_cpu.v:389.6-389.24" *)
  wire id_ex_flush_branch;
  (* src = "../src/top/riscv_cpu.v:388.6-388.24" *)
  wire id_ex_flush_hazard;
  (* src = "../src/top/riscv_cpu.v:78.13-78.25" *)
  wire [2:0] id_ex_funct3;
  (* src = "../src/top/riscv_cpu.v:79.13-79.25" *)
  wire [6:0] id_ex_funct7;
  (* src = "../src/top/riscv_cpu.v:71.13-71.28" *)
  wire [31:0] id_ex_immediate;
  (* src = "../src/top/riscv_cpu.v:86.13-86.23" *)
  wire id_ex_jump;
  (* src = "../src/top/riscv_cpu.v:87.13-87.32" *)
  wire id_ex_load_unsigned;
  (* src = "../src/top/riscv_cpu.v:82.13-82.27" *)
  wire id_ex_mem_read;
  (* src = "../src/top/riscv_cpu.v:83.13-83.28" *)
  wire id_ex_mem_write;
  (* src = "../src/top/riscv_cpu.v:68.13-68.21" *)
  wire [31:0] id_ex_pc;
  (* src = "../src/top/riscv_cpu.v:200.13-200.27" *)
  wire [31:0] id_ex_pc_plus4;
  (* src = "../src/top/riscv_cpu.v:77.13-77.21" *)
  wire [4:0] id_ex_rd;
  (* src = "../src/top/riscv_cpu.v:75.13-75.22" *)
  wire [4:0] id_ex_rs1;
  (* src = "../src/top/riscv_cpu.v:69.13-69.27" *)
  wire [31:0] id_ex_rs1_data;
  (* src = "../src/top/riscv_cpu.v:76.13-76.22" *)
  wire [4:0] id_ex_rs2;
  (* src = "../src/top/riscv_cpu.v:70.13-70.27" *)
  wire [31:0] id_ex_rs2_data;
  (* src = "../src/top/riscv_cpu.v:89.13-89.38" *)
  wire id_ex_use_pc_as_operand_a;
  (* src = "../src/top/riscv_cpu.v:88.13-88.25" *)
  wire [1:0] id_ex_wb_sel;
  (* src = "../src/top/riscv_cpu.v:65.13-65.24" *)
  wire if_id_flush;
  (* src = "../src/top/riscv_cpu.v:62.13-62.30" *)
  wire [31:0] if_id_instruction;
  (* src = "../src/top/riscv_cpu.v:61.13-61.21" *)
  wire [31:0] if_id_pc;
  (* src = "../src/top/riscv_cpu.v:64.13-64.24" *)
  wire if_id_write;
  (* src = "../src/top/riscv_cpu.v:36.13-36.22" *)
  wire [31:0] immediate;
  (* src = "../src/top/riscv_cpu.v:15.13-15.24" *)
  wire [31:0] instruction;
  (* src = "../src/top/riscv_cpu.v:29.6-29.10" *)
  wire jump;
  (* src = "../src/top/riscv_cpu.v:30.6-30.19" *)
  wire load_unsigned;
  (* src = "../src/top/riscv_cpu.v:25.6-25.14" *)
  wire mem_read;
  (* src = "../src/top/riscv_cpu.v:105.13-105.30" *)
  wire [31:0] mem_wb_alu_result;
  (* src = "../src/top/riscv_cpu.v:268.6-268.18" *)
  wire mem_wb_flush;
  (* src = "../src/top/riscv_cpu.v:107.13-107.29" *)
  wire [31:0] mem_wb_immediate;
  (* src = "../src/top/riscv_cpu.v:106.13-106.28" *)
  wire [31:0] mem_wb_pc_plus4;
  (* src = "../src/top/riscv_cpu.v:108.13-108.22" *)
  wire [4:0] mem_wb_rd;
  (* src = "../src/top/riscv_cpu.v:103.13-103.26" *)
  wire [1:0] mem_wb_wb_sel;
  (* src = "../src/top/riscv_cpu.v:26.6-26.15" *)
  wire mem_write;
  (* src = "../src/top/riscv_cpu.v:52.6-52.9" *)
  wire neq;
  (* src = "../src/top/riscv_cpu.v:12.13-12.20" *)
  wire [31:0] next_pc;
  (* src = "../src/top/riscv_cpu.v:17.12-17.18" *)
  wire [6:0] opcode;
  (* src = "../src/top/riscv_cpu.v:11.13-11.15" *)
  wire [31:0] pc;
  (* src = "../src/top/riscv_cpu.v:13.13-13.21" *)
  wire [31:0] pc_plus4;
  (* src = "../src/top/riscv_cpu.v:63.13-63.21" *)
  wire pc_write;
  (* src = "../src/top/riscv_cpu.v:18.12-18.14" *)
  wire [4:0] rd;
  (* src = "../src/top/riscv_cpu.v:24.6-24.15" *)
  wire reg_write;
  (* src = "../src/top/riscv_cpu.v:20.12-20.15" *)
  wire [4:0] rs1;
  (* src = "../src/top/riscv_cpu.v:33.13-33.21" *)
  wire [31:0] rs1_data;
  (* src = "../src/top/riscv_cpu.v:21.12-21.15" *)
  wire [4:0] rs2;
  (* src = "../src/top/riscv_cpu.v:34.13-34.21" *)
  wire [31:0] rs2_data;
  (* src = "../src/top/riscv_cpu.v:57.6-57.25" *)
  wire use_pc_as_operand_a;
  (* src = "../src/top/riscv_cpu.v:49.12-49.18" *)
  wire [1:0] wb_sel;
  (* src = "../src/top/riscv_cpu.v:59.13-59.27" *)
  wire [31:0] writeback_data;
  assign \PC.next_pc [2] = ~\PC.pc [2];
  assign _003_ = \PC.pc [3] & \PC.pc [2];
  assign _004_ = \PC.pc [4] & _003_;
  assign _005_ = \PC.pc [5] & _004_;
  assign _006_ = \PC.pc [6] & _005_;
  assign _007_ = \PC.pc [7] & _006_;
  assign _008_ = \PC.pc [8] & _007_;
  assign _009_ = \PC.pc [9] & _008_;
  assign \PC.next_pc [9] = \PC.pc [9] ^ _008_;
  assign _010_ = \PC.pc [10] & _009_;
  assign _011_ = \PC.pc [11] & _010_;
  assign _012_ = \PC.pc [12] & _011_;
  assign _013_ = \PC.pc [13] & _012_;
  assign _014_ = \PC.pc [14] & _013_;
  assign _015_ = \PC.pc [15] & _014_;
  assign _016_ = \PC.pc [16] & _015_;
  assign _017_ = \PC.pc [17] & _016_;
  assign \PC.next_pc [17] = \PC.pc [17] ^ _016_;
  assign _018_ = \PC.pc [18] & _017_;
  assign _019_ = \PC.pc [19] & _018_;
  assign _020_ = \PC.pc [20] & _019_;
  assign _021_ = \PC.pc [21] & _020_;
  assign \PC.next_pc [21] = \PC.pc [21] ^ _020_;
  assign \PC.next_pc [11] = \PC.pc [11] ^ _010_;
  assign \PC.next_pc [7] = \PC.pc [7] ^ _006_;
  assign \PC.next_pc [6] = \PC.pc [6] ^ _005_;
  assign \PC.next_pc [19] = \PC.pc [19] ^ _018_;
  assign \PC.next_pc [4] = \PC.pc [4] ^ _003_;
  assign \PC.next_pc [13] = \PC.pc [13] ^ _012_;
  assign _022_ = \PC.pc [22] & _021_;
  assign \PC.next_pc [22] = \PC.pc [22] ^ _021_;
  assign \PC.next_pc [20] = \PC.pc [20] ^ _019_;
  assign _023_ = \PC.pc [23] & _022_;
  assign \PC.next_pc [23] = \PC.pc [23] ^ _022_;
  assign _024_ = \PC.pc [24] & _023_;
  assign _025_ = \PC.pc [25] & _024_;
  assign _026_ = \PC.pc [26] & _025_;
  assign _027_ = \PC.pc [27] & _026_;
  assign \PC.next_pc [27] = \PC.pc [27] ^ _026_;
  assign \PC.next_pc [24] = \PC.pc [24] ^ _023_;
  assign \PC.next_pc [25] = \PC.pc [25] ^ _024_;
  assign \PC.next_pc [18] = \PC.pc [18] ^ _017_;
  assign \PC.next_pc [5] = \PC.pc [5] ^ _004_;
  assign _000_ = \PC.pc [28] & _027_;
  assign _001_ = \PC.pc [29] & _000_;
  assign _002_ = ~(\PC.pc [30] & _001_);
  assign \PC.next_pc [30] = \PC.pc [30] ^ _001_;
  assign \PC.next_pc [12] = \PC.pc [12] ^ _011_;
  assign \PC.next_pc [15] = \PC.pc [15] ^ _014_;
  assign \PC.next_pc [10] = \PC.pc [10] ^ _009_;
  assign \PC.next_pc [26] = \PC.pc [26] ^ _025_;
  assign \PC.next_pc [8] = \PC.pc [8] ^ _007_;
  assign \PC.next_pc [31] = ~(\PC.pc [31] ^ _002_);
  assign \PC.next_pc [28] = \PC.pc [28] ^ _027_;
  assign \PC.next_pc [16] = \PC.pc [16] ^ _015_;
  assign \PC.next_pc [29] = \PC.pc [29] ^ _000_;
  assign \PC.next_pc [3] = \PC.pc [3] ^ \PC.pc [2];
  assign \PC.next_pc [14] = \PC.pc [14] ^ _013_;
  reg \PC.pc_reg[2] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[2]  <= 1'h0;
    else \PC.pc_reg[2]  <= \PC.next_pc [2];
  assign \PC.pc [2] = \PC.pc_reg[2] ;
  reg \PC.pc_reg[3] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[3]  <= 1'h0;
    else \PC.pc_reg[3]  <= \PC.next_pc [3];
  assign \PC.pc [3] = \PC.pc_reg[3] ;
  reg \PC.pc_reg[4] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[4]  <= 1'h0;
    else \PC.pc_reg[4]  <= \PC.next_pc [4];
  assign \PC.pc [4] = \PC.pc_reg[4] ;
  reg \PC.pc_reg[5] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[5]  <= 1'h0;
    else \PC.pc_reg[5]  <= \PC.next_pc [5];
  assign \PC.pc [5] = \PC.pc_reg[5] ;
  reg \PC.pc_reg[6] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[6]  <= 1'h0;
    else \PC.pc_reg[6]  <= \PC.next_pc [6];
  assign \PC.pc [6] = \PC.pc_reg[6] ;
  reg \PC.pc_reg[7] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[7]  <= 1'h0;
    else \PC.pc_reg[7]  <= \PC.next_pc [7];
  assign \PC.pc [7] = \PC.pc_reg[7] ;
  reg \PC.pc_reg[8] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[8]  <= 1'h0;
    else \PC.pc_reg[8]  <= \PC.next_pc [8];
  assign \PC.pc [8] = \PC.pc_reg[8] ;
  reg \PC.pc_reg[9] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[9]  <= 1'h0;
    else \PC.pc_reg[9]  <= \PC.next_pc [9];
  assign \PC.pc [9] = \PC.pc_reg[9] ;
  reg \PC.pc_reg[10] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[10]  <= 1'h0;
    else \PC.pc_reg[10]  <= \PC.next_pc [10];
  assign \PC.pc [10] = \PC.pc_reg[10] ;
  reg \PC.pc_reg[11] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[11]  <= 1'h0;
    else \PC.pc_reg[11]  <= \PC.next_pc [11];
  assign \PC.pc [11] = \PC.pc_reg[11] ;
  reg \PC.pc_reg[12] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[12]  <= 1'h0;
    else \PC.pc_reg[12]  <= \PC.next_pc [12];
  assign \PC.pc [12] = \PC.pc_reg[12] ;
  reg \PC.pc_reg[13] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[13]  <= 1'h0;
    else \PC.pc_reg[13]  <= \PC.next_pc [13];
  assign \PC.pc [13] = \PC.pc_reg[13] ;
  reg \PC.pc_reg[14] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[14]  <= 1'h0;
    else \PC.pc_reg[14]  <= \PC.next_pc [14];
  assign \PC.pc [14] = \PC.pc_reg[14] ;
  reg \PC.pc_reg[15] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[15]  <= 1'h0;
    else \PC.pc_reg[15]  <= \PC.next_pc [15];
  assign \PC.pc [15] = \PC.pc_reg[15] ;
  reg \PC.pc_reg[16] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[16]  <= 1'h0;
    else \PC.pc_reg[16]  <= \PC.next_pc [16];
  assign \PC.pc [16] = \PC.pc_reg[16] ;
  reg \PC.pc_reg[17] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[17]  <= 1'h0;
    else \PC.pc_reg[17]  <= \PC.next_pc [17];
  assign \PC.pc [17] = \PC.pc_reg[17] ;
  reg \PC.pc_reg[18] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[18]  <= 1'h0;
    else \PC.pc_reg[18]  <= \PC.next_pc [18];
  assign \PC.pc [18] = \PC.pc_reg[18] ;
  reg \PC.pc_reg[19] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[19]  <= 1'h0;
    else \PC.pc_reg[19]  <= \PC.next_pc [19];
  assign \PC.pc [19] = \PC.pc_reg[19] ;
  reg \PC.pc_reg[20] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[20]  <= 1'h0;
    else \PC.pc_reg[20]  <= \PC.next_pc [20];
  assign \PC.pc [20] = \PC.pc_reg[20] ;
  reg \PC.pc_reg[21] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[21]  <= 1'h0;
    else \PC.pc_reg[21]  <= \PC.next_pc [21];
  assign \PC.pc [21] = \PC.pc_reg[21] ;
  reg \PC.pc_reg[22] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[22]  <= 1'h0;
    else \PC.pc_reg[22]  <= \PC.next_pc [22];
  assign \PC.pc [22] = \PC.pc_reg[22] ;
  reg \PC.pc_reg[23] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[23]  <= 1'h0;
    else \PC.pc_reg[23]  <= \PC.next_pc [23];
  assign \PC.pc [23] = \PC.pc_reg[23] ;
  reg \PC.pc_reg[24] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[24]  <= 1'h0;
    else \PC.pc_reg[24]  <= \PC.next_pc [24];
  assign \PC.pc [24] = \PC.pc_reg[24] ;
  reg \PC.pc_reg[25] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[25]  <= 1'h0;
    else \PC.pc_reg[25]  <= \PC.next_pc [25];
  assign \PC.pc [25] = \PC.pc_reg[25] ;
  reg \PC.pc_reg[26] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[26]  <= 1'h0;
    else \PC.pc_reg[26]  <= \PC.next_pc [26];
  assign \PC.pc [26] = \PC.pc_reg[26] ;
  reg \PC.pc_reg[27] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[27]  <= 1'h0;
    else \PC.pc_reg[27]  <= \PC.next_pc [27];
  assign \PC.pc [27] = \PC.pc_reg[27] ;
  reg \PC.pc_reg[28] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[28]  <= 1'h0;
    else \PC.pc_reg[28]  <= \PC.next_pc [28];
  assign \PC.pc [28] = \PC.pc_reg[28] ;
  reg \PC.pc_reg[29] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[29]  <= 1'h0;
    else \PC.pc_reg[29]  <= \PC.next_pc [29];
  assign \PC.pc [29] = \PC.pc_reg[29] ;
  reg \PC.pc_reg[30] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[30]  <= 1'h0;
    else \PC.pc_reg[30]  <= \PC.next_pc [30];
  assign \PC.pc [30] = \PC.pc_reg[30] ;
  reg \PC.pc_reg[31] ;
  (* src = "../src/common/program_counter.v:17.1-24.4" *)
  always @(posedge clk)
    if (!rst_n) \PC.pc_reg[31]  <= 1'h0;
    else \PC.pc_reg[31]  <= \PC.next_pc [31];
  assign \PC.pc [31] = \PC.pc_reg[31] ;
  assign \ID_EX.mem_read_out  = 1'h0;
  assign \EX_MEM.immediate_out  = 32'd0;
  assign \EX_MEM.wb_sel_out  = 2'h0;
  assign \ID_EX.mem_write_out  = 1'h0;
  assign \MEM_STAGE.address  = 32'd0;
  assign \MEM_STAGE.mem_write  = 1'h0;
  assign \EX_MEM.rd  = 5'h00;
  assign \MEM_STAGE.mem_read  = 1'h0;
  assign \IF_ID.rst_n  = rst_n;
  assign \RF.registers[4]  = 32'hxxxxxxxx;
  assign \MEM_STAGE.clk  = clk;
  assign \ID_EX.wb_sel_out  = 2'h0;
  assign \ID_EX.branch_out  = 1'h0;
  assign \ID_EX.rd_out  = 5'h00;
  assign \RF.registers[3]  = 32'hxxxxxxxx;
  assign \ID_EX.jump_out  = 1'h0;
  assign \BRANCH_ADDER.sum  = 32'hxxxxxxxx;
  assign \BRANCH_ADDER.b  = 32'd0;
  assign \IMM_GEN.instruction  = 32'd19;
  assign \IMM_GEN.immediate  = 32'd0;
  assign \IMM_GEN.opcode  = 7'h13;
  assign \FORWARD_B.out  = 32'd0;
  assign \FORWARD_B.sel  = 2'h0;
  assign \FORWARD_B.in3  = 32'd0;
  assign \RF.registers[9]  = 32'hxxxxxxxx;
  assign \MEM_WB.rd_out  = 5'h00;
  assign \MEM_WB.immediate_out  = 32'd0;
  assign \FORWARD_B.in2  = 32'd0;
  assign \MEM_WB.pc_plus4_out  = 32'hxxxxxxxx;
  assign \RF.registers[10]  = 32'hxxxxxxxx;
  assign \FORWARD_B.in1  = 32'd0;
  assign \FORWARD_B.in0  = 32'd0;
  assign \BRANCH_ADDER.a  = 32'hxxxxxxxx;
  assign \RF.registers[2]  = 32'hxxxxxxxx;
  assign \MEM_WB.alu_result_out  = 32'd0;
  assign \ID_EX.rs1_data_out  = 32'd0;
  assign \ID_EX.rs2_data_out  = 32'd0;
  assign \ID_EX.immediate_out  = 32'd0;
  assign \RF.registers[1]  = 32'hxxxxxxxx;
  assign \ID_EX.load_unsigned_out  = 1'h0;
  assign \EX_MEM.rd_out  = 5'h00;
  assign \ID_EX.use_pc_as_operand_a_out  = 1'h0;
  assign \EX_MEM.immediate  = 32'd0;
  assign \ID_EX.rs1_out  = 5'h00;
  assign \ID_EX.funct3_out  = 3'h0;
  assign \MEM_WB.wb_sel_out  = 2'h0;
  assign \RF.registers[5]  = 32'hxxxxxxxx;
  assign \MEM_WB.rd  = 5'h00;
  assign \ID_EX.funct7_out  = 7'h00;
  assign \EX_MEM.pc_plus4  = 32'hxxxxxxxx;
  assign \MEM_WB.immediate  = 32'd0;
  assign \MEM_WB.pc_plus4  = 32'hxxxxxxxx;
  assign \MEM_WB.alu_result  = 32'd0;
  assign \ID_EX.pc_out  = 32'hxxxxxxxx;
  assign \RF.registers[8]  = 32'hxxxxxxxx;
  assign \RF.registers[13]  = 32'hxxxxxxxx;
  assign \PC_ADDER.sum  = { \PC.next_pc [31:2], 2'h0 };
  assign \PC_ADDER.b  = 32'd4;
  assign \EX_STAGE.ALU.result  = 32'd0;
  assign \IF_ID.stall  = 1'h0;
  assign \HAZARD.id_ex_flush  = 1'h0;
  assign \HAZARD.if_id_write  = 1'h1;
  assign \HAZARD.pc_write  = 1'h1;
  assign \PC_ADDER.a  = { \PC.pc [31:2], 2'h0 };
  assign \HAZARD.if_id_rs2  = 5'h00;
  assign \HAZARD.if_id_rs1  = 5'h00;
  assign \EX_STAGE.ALU.alu_control  = 4'h0;
  assign \CMP.a  = 32'd0;
  assign \CMP.b  = 32'd0;
  assign \CMP.equal  = 1'h1;
  assign \CMP.not_equal  = 1'h0;
  assign \MEM_WB.wb_sel  = 2'h0;
  assign \EX_MEM.rs2_data  = 32'd0;
  assign \EX_MEM.alu_result  = 32'd0;
  assign \EX_STAGE.ALU.operand_b  = 32'd0;
  assign \EX_MEM.wb_sel  = 2'h0;
  assign \EX_STAGE.ALU.operand_a  = 32'd0;
  assign \ALU_CTRL.alu_op  = 2'h2;
  assign \ID_EX.rd  = 5'h00;
  assign \ID_EX.clk  = clk;
  assign \MEM_WB.flush  = 1'h0;
  assign \EX_MEM.mem_write  = 1'h0;
  assign \EX_MEM.mem_read  = 1'h0;
  assign \ID_EX.rst_n  = rst_n;
  assign \ALU_CTRL.funct3  = 3'h0;
  assign \ALU_CTRL.funct7  = 7'h00;
  assign \ID_EX.flush  = 1'h0;
  assign \ALU_CTRL.alu_control  = 4'h0;
  assign \MEM_WB.rst_n  = rst_n;
  assign \ID_EX.rs2_out  = 5'h00;
  assign \EX_STAGE.rs1_data  = 32'd0;
  assign \RF.i  = 32'd32;
  assign \RF.rs2_data  = 32'd0;
  assign \RF.rs2_addr  = 5'h00;
  assign \ID_EX.reg_write  = 1'h1;
  assign \EX_MEM.flush  = 1'h0;
  assign \EX_MEM.rst_n  = rst_n;
  assign \RF.rs1_data  = 32'd0;
  assign \RF.rs1_addr  = 5'h00;
  assign \ID_EX.mem_read  = 1'h0;
  assign \ID_EX.mem_write  = 1'h0;
  assign \BRANCH.branch_taken  = 1'h0;
  assign \RF.rd_data  = 32'd0;
  assign \RF.rd_addr  = 5'h00;
  assign \ID_EX.rs2  = 5'h00;
  assign \MEM_WB.clk  = clk;
  assign \ID_EX_PC4.a  = 32'hxxxxxxxx;
  assign \ID_EX.alu_src  = 1'h1;
  assign \RF.rst_n  = rst_n;
  assign \RF.clk  = clk;
  assign \EX_STAGE.pc  = 32'hxxxxxxxx;
  assign \BRANCH.not_equal  = 1'h0;
  assign \BRANCH.equal  = 1'h1;
  assign \EX_MEM.clk  = clk;
  assign \EX_STAGE.use_pc_as_operand_a  = 1'h0;
  assign \IF_ID.flush  = 1'h0;
  assign \BRANCH.funct3  = 3'h0;
  assign \BRANCH.branch  = 1'h0;
  assign \MEM_STAGE.DMEM.clk  = clk;
  assign \RF.registers[14]  = 32'hxxxxxxxx;
  assign \EX_MEM.mem_write_out  = 1'h0;
  assign \MEM_STAGE.DMEM.mem_read  = 1'h0;
  assign \MEM_STAGE.DMEM.mem_write  = 1'h0;
  assign \MEM_STAGE.DMEM.address  = 32'd0;
  assign \RF.registers[11]  = 32'hxxxxxxxx;
  assign \EX_MEM.alu_result_out  = 32'd0;
  assign \ID_EX.rs1  = 5'h00;
  assign \IF_ID.pc  = { \PC.pc [31:2], 2'h0 };
  assign \ID_EX_PC4.b  = 32'd4;
  assign \ID_EX_PC4.sum  = 32'hxxxxxxxx;
  assign \FORWARD.ex_mem_rd  = 5'h00;
  assign \ID_EX.funct3  = 3'h0;
  assign \FORWARD.mem_wb_rd  = 5'h00;
  assign \FORWARD_A.out  = 32'd0;
  assign \FORWARD_A.sel  = 2'h0;
  assign \FORWARD_A.in3  = 32'd0;
  assign \FORWARD_A.in2  = 32'd0;
  assign \FORWARD_A.in1  = 32'd0;
  assign \FORWARD_A.in0  = 32'd0;
  assign \RF.registers[30]  = 32'hxxxxxxxx;
  assign \RF.registers[29]  = 32'hxxxxxxxx;
  assign \MEM_STAGE.DMEM.i  = 32'd256;
  assign \MEM_STAGE.DMEM.word_addr  = 10'h000;
  assign \IF_ID.instruction  = 32'd19;
  assign \ID_EX.alu_op  = 2'h2;
  assign \ID_EX.funct7  = 7'h00;
  assign \RF.registers[28]  = 32'hxxxxxxxx;
  assign \EX_STAGE.operand_b  = 32'd0;
  assign \CONTROL.opcode  = 7'h13;
  assign \CONTROL.reg_write  = 1'h1;
  assign \CONTROL.mem_read  = 1'h0;
  assign \CONTROL.mem_write  = 1'h0;
  assign \CONTROL.alu_src  = 1'h1;
  assign \CONTROL.alu_op  = 2'h2;
  assign \CONTROL.branch  = 1'h0;
  assign \CONTROL.jump  = 1'h0;
  assign \CONTROL.load_unsigned  = 1'h0;
  assign \CONTROL.wb_sel  = 2'h0;
  assign \CONTROL.use_pc_as_operand_a  = 1'h0;
  assign \RF.registers[27]  = 32'hxxxxxxxx;
  assign \EX_STAGE.operand_a  = 32'd0;
  assign \WB_STAGE.writeback_data  = 32'd0;
  assign \FORWARD.id_ex_rs1  = 5'h00;
  assign \RF.registers[26]  = 32'hxxxxxxxx;
  assign \ID_EX.pc  = 32'hxxxxxxxx;
  assign \RF.registers[25]  = 32'hxxxxxxxx;
  assign \WB_STAGE.wb_sel  = 2'h0;
  assign \IF_ID.clk  = clk;
  assign \RF.registers[24]  = 32'hxxxxxxxx;
  assign \ID_EX.rs1_data  = 32'd0;
  assign \ID_EX.wb_sel  = 2'h0;
  assign \HAZARD.id_ex_rd  = 5'h00;
  assign \WB_STAGE.immediate  = 32'd0;
  assign \FORWARD.id_ex_rs2  = 5'h00;
  assign \RF.registers[23]  = 32'hxxxxxxxx;
  assign \WB_STAGE.pc_plus4  = 32'hxxxxxxxx;
  assign \HAZARD.id_ex_mem_read  = 1'h0;
  assign \RF.registers[22]  = 32'hxxxxxxxx;
  assign \ID_EX.branch  = 1'h0;
  assign \EX_STAGE.alu_control  = 4'h0;
  assign \FLUSH.id_ex_flush  = 1'h0;
  assign \RF.registers[6]  = 32'hxxxxxxxx;
  assign \FLUSH.if_id_flush  = 1'h0;
  assign \ID_EX.jump  = 1'h0;
  assign \IF_ID.instruction_out  = 32'd19;
  assign \FLUSH.jump  = 1'h0;
  assign \RF.registers[21]  = 32'hxxxxxxxx;
  assign \EX_STAGE.immediate  = 32'd0;
  assign \RF.registers[20]  = 32'hxxxxxxxx;
  assign \ID_EX.load_unsigned  = 1'h0;
  assign \WB_STAGE.alu_result  = 32'd0;
  assign \FLUSH.branch_taken  = 1'h0;
  assign \RF.registers[12]  = 32'hxxxxxxxx;
  assign \RF.registers[19]  = 32'hxxxxxxxx;
  assign \EX_MEM.mem_read_out  = 1'h0;
  assign \DECODER.instruction  = 32'd19;
  assign \DECODER.opcode  = 7'h13;
  assign \DECODER.rd  = 5'h00;
  assign \DECODER.funct3  = 3'h0;
  assign \DECODER.rs1  = 5'h00;
  assign \DECODER.rs2  = 5'h00;
  assign \DECODER.funct7  = 7'h00;
  assign \IMEM.pc  = { \PC.pc [31:2], 2'h0 };
  assign \IMEM.instruction  = 32'd19;
  assign \IMEM.i  = 32'd1024;
  assign \IMEM.word_addr  = \PC.pc [11:2];
  assign \PC.clk  = clk;
  assign \PC.rst_n  = rst_n;
  assign \PC.pc_en  = 1'h1;
  assign \PC.next_pc [1:0] = 2'hx;
  assign \PC.pc [1:0] = 2'h0;
  assign \IF_ID.pc_out  = 32'hxxxxxxxx;
  assign id_ex_flush_branch = 1'h0;
  assign id_ex_flush_hazard = 1'h0;
  assign mem_wb_flush = 1'h0;
  assign ex_mem_flush = 1'h0;
  assign id_ex_pc_plus4 = 32'hxxxxxxxx;
  assign forward_rs2 = 32'd0;
  assign forward_rs1 = 32'd0;
  assign forward_b = 2'h0;
  assign forward_a = 2'h0;
  assign mem_wb_rd = 5'h00;
  assign mem_wb_immediate = 32'd0;
  assign mem_wb_pc_plus4 = 32'hxxxxxxxx;
  assign mem_wb_alu_result = 32'd0;
  assign \RF.registers[18]  = 32'hxxxxxxxx;
  assign mem_wb_wb_sel = 2'h0;
  assign \EX_MEM.pc_plus4_out  = 32'hxxxxxxxx;
  assign ex_mem_rd = 5'h00;
  assign ex_mem_immediate = 32'd0;
  assign ex_mem_pc_plus4 = 32'hxxxxxxxx;
  assign \EX_STAGE.alu_result  = 32'd0;
  assign ex_mem_alu_result = 32'd0;
  assign ex_mem_wb_sel = 2'h0;
  assign ex_mem_mem_write = 1'h0;
  assign ex_mem_mem_read = 1'h0;
  assign \ID_EX.use_pc_as_operand_a  = 1'h0;
  assign id_ex_flush = 1'h0;
  assign id_ex_use_pc_as_operand_a = 1'h0;
  assign id_ex_wb_sel = 2'h0;
  assign id_ex_load_unsigned = 1'h0;
  assign id_ex_jump = 1'h0;
  assign id_ex_branch = 1'h0;
  assign \ID_EX.immediate  = 32'd0;
  assign id_ex_mem_write = 1'h0;
  assign id_ex_mem_read = 1'h0;
  assign \EX_STAGE.rs2_data  = 32'd0;
  assign id_ex_funct7 = 7'h00;
  assign id_ex_funct3 = 3'h0;
  assign id_ex_rd = 5'h00;
  assign id_ex_rs2 = 5'h00;
  assign id_ex_rs1 = 5'h00;
  assign \RF.registers[17]  = 32'hxxxxxxxx;
  assign id_ex_immediate = 32'd0;
  assign id_ex_rs2_data = 32'd0;
  assign id_ex_rs1_data = 32'd0;
  assign id_ex_pc = 32'hxxxxxxxx;
  assign if_id_flush = 1'h0;
  assign if_id_write = 1'h1;
  assign pc_write = 1'h1;
  assign if_id_instruction = 32'd19;
  assign if_id_pc = 32'hxxxxxxxx;
  assign writeback_data = 32'd0;
  assign use_pc_as_operand_a = 1'h0;
  assign \FORWARD.forward_a  = 2'h0;
  assign \RF.registers[7]  = 32'hxxxxxxxx;
  assign \RF.registers[16]  = 32'hxxxxxxxx;
  assign neq = 1'h0;
  assign eq = 1'h1;
  assign wb_sel = 2'h0;
  assign branch_taken = 1'h0;
  assign branch_target = 32'hxxxxxxxx;
  assign \ID_EX.rs2_data  = 32'd0;
  assign alu_control_signal = 4'h0;
  assign \RF.registers[15]  = 32'hxxxxxxxx;
  assign \FORWARD.forward_b  = 2'h0;
  assign alu_result = 32'd0;
  assign immediate = 32'd0;
  assign rs2_data = 32'd0;
  assign rs1_data = 32'd0;
  assign alu_op = 2'h2;
  assign load_unsigned = 1'h0;
  assign jump = 1'h0;
  assign branch = 1'h0;
  assign alu_src = 1'h1;
  assign mem_write = 1'h0;
  assign mem_read = 1'h0;
  assign reg_write = 1'h1;
  assign funct7 = 7'h00;
  assign rs2 = 5'h00;
  assign rs1 = 5'h00;
  assign funct3 = 3'h0;
  assign rd = 5'h00;
  assign opcode = 7'h13;
  assign instruction = 32'd19;
  assign pc_plus4 = { \PC.next_pc [31:2], 2'h0 };
  assign next_pc = { \PC.next_pc [31:2], 2'hx };
  assign pc = { \PC.pc [31:2], 2'h0 };
  assign debug_writeback_data = 32'd0;
  assign debug_instruction = 32'd19;
  assign debug_pc = { \PC.pc [31:2], 2'h0 };
endmodule
