###############################################################################
# Created by write_sdc
###############################################################################
current_design riscv_cpu
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_uncertainty 0.2000 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_instruction[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_pc[9]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[0]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[10]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[11]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[12]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[13]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[14]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[15]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[16]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[17]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[18]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[19]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[1]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[20]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[21]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[22]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[23]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[24]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[25]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[26]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[27]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[28]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[29]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[2]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[30]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[31]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[3]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[4]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[5]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[6]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[7]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[8]}]
set_output_delay 0.0000 -clock [get_clocks {clk}] -add_delay [get_ports {debug_writeback_data[9]}]
###############################################################################
# Environment
###############################################################################
###############################################################################
# Design Rules
###############################################################################
